name: Deploy to GH-Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install deps, build site
        run: |
          npm install
          npm run build

      - name: Deploy site
        uses: fregante/setup-git-user@v1
      - run: |
          cd dist/
          git checkout gh-pages
          git commit -m "Deploy Site"
          git push
