name: Deploy to GH-Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install deps, build site
        run: |
          npm install
          npm run build

      - name: Setup Git User
        uses: fregante/setup-git-user@v1

      - name: Deploy Site
        run: |
          cd dist/
          git checkout gh-pages
          git add .
          git commit -m "Deploy Site"
          git push
